version: "3.8"
services:
  app:
    image: aydo/be:latest
    build:
      context: .
      dockerfile: be.Dockerfile
    ports:
      - "8000:8000"
    platform: linux/amd64
    env_file:
      - .env
  
  frontend:
    image: aydo/fe:latest
    build:
      context: .
      dockerfile: fe.Dockerfile
    ports:
      - "8501:8501"
    platform: linux/amd64
    env_file:
      - .env
      